export const goodsDetailsOption = {
  height: "auto",
  calcHeight: 10,
  dialogDrag: true,
  lazy: true,
  tip: false,
  simplePage: true,
  searchShow: false,
  searchMenuSpan: 4,
  dialogWidth: "50%",
  tree: true,
  border: true,
  index: true,
  selection: true,
  // addBtn: false,
  viewBtn: true,
  // editBtn: false,
  // delBtn: false,
  menuWidth: 200,
  emptyBtn: false,
  submitBtn: false,
  disabled: true,
  dialogClickModal: false,
  column: [
    {
      label: "详情id",
      prop: "sid",
      hide: true,
      display: false,
    },
    {
      label: "商品id",
      prop: "cid",
      hide: true,
      display: false,
    },
    //     "intr": "商品简介商品简介商品简介", //商品简介(富文本)
    // "desc": "商品详情商品详情商品详情", //商品详情
    // "terms": "使用条款使用条款使用条款", //使用条款
    {
      label: "商品简介",
      prop: "intr",
      hide: true,
      type: "textarea",
      formslot: true,
      addDisplay: false,
      span: 24,
      rules: [
        {
          required: true,
          message: "请输入商品简介",
          trigger: "blur",
        },
      ],
    },
    {
      label: "商品详情",
      prop: "desc",
      hide: true,
      type: "textarea",
      span: 24,
      formslot: true,
      addDisplay: false,
      rules: [
        {
          required: true,
          message: "请输入商品详情",
          trigger: "blur",
        },
      ],
    },
    {
      label: "使用条款",
      prop: "terms",
      hide: true,
      type: "textarea",
      span: 24,
      formslot: true,
      addDisplay: false,
      rules: [
        {
          required: true,
          message: "请输入使用条款",
          trigger: "blur",
        },
      ],
    },
    {
      label: "创建时间",
      prop: "credate",
      width: 140,
      display: false,
    },
    {
      label: "修改时间",
      prop: "upddate",
      width: 140,
      display: false,
    },
  ],
};

export const goodsEditOption = {
  height: "auto",
  calcHeight: 10,
  dialogDrag: true,
  lazy: true,
  tip: false,
  simplePage: true,
  searchShow: false,
  searchMenuSpan: 4,
  dialogWidth: "50%",
  tree: true,
  border: true,
  index: true,
  selection: true,
  addBtn: true,
  viewBtn: true,
  // editBtn: false,
  // delBtn: false,
  menuWidth: 200,
  dialogClickModal: false,
  column: [
    {
      label: "详情id",
      prop: "sid",
      hide: true,
      display: false,
    },
    {
      label: "商品id",
      prop: "cid",
      hide: true,
      display: false,
    },
    {
      label: "商品简介",
      prop: "intr",
      hide: true,
      type: "textarea",
      formslot: true,
      addDisplay: false,
      span: 24,
      rows: 18,
      rules: [
        {
          required: true,
          message: "请输入商品简介",
          trigger: "blur",
        },
      ],
    },
    {
      label: "商品详情",
      prop: "desc",
      hide: true,
      type: "textarea",
      span: 24,
      formslot: true,
      addDisplay: false,
      rules: [
        {
          required: true,
          message: "请输入商品详情",
          trigger: "blur",
        },
      ],
    },
    {
      label: "使用条款",
      prop: "terms",
      hide: true,
      type: "textarea",
      span: 24,
      formslot: true,
      addDisplay: false,
      rules: [
        {
          required: true,
          message: "请输入使用条款",
          trigger: "blur",
        },
      ],
    },
    {
      label: "创建时间",
      prop: "credate",
      width: 140,
      display: false,
    },
    {
      label: "修改时间",
      prop: "upddate",
      width: 140,
      display: false,
    },
  ],
};

export const goodsAddOption = {
  height: "auto",
  calcHeight: 10,
  dialogDrag: true,
  lazy: true,
  tip: false,
  simplePage: true,
  searchShow: false,
  searchMenuSpan: 4,
  dialogWidth: "50%",
  tree: true,
  border: true,
  index: true,
  selection: true,
  addBtn: true,
  viewBtn: true,
  // editBtn: false,
  // delBtn: false,
  menuWidth: 200,
  dialogClickModal: false,
  column: [
    {
      label: "详情id",
      prop: "sid",
      hide: true,
      display: false,
    },
    {
      label: "商品id",
      prop: "cid",
      hide: true,
      display: false,
    },
    {
      label: "商品简介",
      prop: "intr",
      hide: true,
      // type: 'textarea',
      formslot: true,
      // addDisplay: false,
      span: 24,
    },
    {
      label: "商品详情",
      prop: "desc",
      hide: true,
      type: "textarea",
      span: 24,
      formslot: true,
      // addDisplay: false,
    },
    {
      label: "使用条款",
      prop: "terms",
      hide: true,
      type: "textarea",
      span: 24,
      formslot: true,
    },
    {
      label: "创建时间",
      prop: "credate",
      width: 140,
      display: false,
    },
    {
      label: "修改时间",
      prop: "upddate",
      width: 140,
      display: false,
    },
  ],
};
