export const mainOption = {
  height: "auto",
  calcHeight: 10,
  dialogDrag: true,
  lazy: true,
  tip: false,
  simplePage: true,
  searchShow: false,
  searchMenuSpan: 4,
  dialogWidth: "50%",
  tree: true,
  border: true,
  index: true,
  selection: true,
  // addBtn: false,
  viewBtn: false,
  editBtn: false,
  delBtn: false,
  menuWidth: 120,
  dialogClickModal: false,
  column: [
    {
      label: "图片id",
      prop: "pid",
      hide: true,
      addDisplay:false,
      display:false,
    },
    {
      label: "商品id",
      prop: "cid",
      hide: true,
      addDisplay:false,
      editDisplay:false,
      display:false,
    },
    {
      label: "图片",
      prop: "purlList",
      maxlength: 64,
      showWordLimit: true,
      viewDisplay: false,
      editDisplay:false,
      span: 24,
      hide: true,
      formslot: true,
      slot: true,
    },
    {
      label: "图片",
      prop: "purl",
      maxlength: 64,
      addDisplay:false,
      showWordLimit: true,
      span: 24,
      formslot: true,
      slot: true,
    },
    {
      label: "状态",
      prop: "status",
      type: "select",
      slot: true,
      width: 180,
      span: 24,
      align: "center",
      addDisplay:false,
      search: true,
      dicData: [
        {
          label: "启用",
          value: '1',
        },
        {
          label: "禁用",
          value: '2',
        },
      ],
      rules: [
        {
          required: true,
          message: "请选择状态",
          trigger: "blur",
        },
      ],
    },
    {
      label: "创建时间",
      prop: "credate",
      width: 160,
      // hide: true,
      display: false,
    },
    {
      label: "修改时间",
      prop: "upddate",
      width: 160,
      // hide: true,
      display: false,
    },
  ],
};